### PR TITLE
Consider invalid Raptor $shard_uuid value as false predicate

### LINKED ISSUE #3951: Categorize exception for invalid Raptor $shard_uuid value
```sql
SELECT * FROM orders WHERE "$shard_uuid" = '4c9415cb-c37d-4bad-b8ac-952670948fa1 ';
```

```
java.lang.NumberFormatException: For input string: "952670948fa1 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:776)
	at java.lang.Long.decode(Long.java:928)
	at java.util.UUID.fromString(UUID.java:206)
	at com.facebook.presto.raptor.util.UuidUtil.uuidStringToBytes(UuidUtil.java:138)
	at com.facebook.presto.raptor.metadata.ShardPredicate.create(ShardPredicate.java:113)
	at com.facebook.presto.raptor.metadata.ShardIterator.<init>(ShardIterator.java:61)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.getShardNodes(DatabaseShardManager.java:338)
	at com.facebook.presto.raptor.RaptorSplitManager$RaptorSplitSource.<init>(RaptorSplitManager.java:136)
	at com.facebook.presto.raptor.RaptorSplitManager.getSplits(RaptorSplitManager.java:94)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:59)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:99)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:85)
	at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:149)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:85)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:207)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:85)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:71)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:76)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:215)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$213(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by haozhun**
Before this fix, it throws an uncategorized exception when invalid Raptor $shard_uuid is encountered.

Fixes #3951

### CODE REVIEW

File: presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java [hunk 1]
```diff
@@ -74,12 +76,22 @@ public void testShardUuidHiddenColumn()
...
         List<MaterializedRow> actualRows = actualResults.getMaterializedRows();
+        String arbitraryUuid = null;
         for (MaterializedRow row : actualRows) {
             Object uuid = row.getField(2);
             assertInstanceOf(uuid, String.class);
             // check that the string can be parsed into a UUID
             UUID.fromString((String) uuid);
+            arbitraryUuid = (String) uuid;
         }
+        assertNotNull(arbitraryUuid);
```
Comment (electrum) [inline presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java]: This is just asserting we had a row. If it was null or invalid, the loop would throw.

So before the loop, assert actualRows is not empty.

Comment (electrum) [inline presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java]: Nevermind, I see its used below

File: presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java [hunk 2]
```diff
@@ -74,12 +76,22 @@ public void testShardUuidHiddenColumn()
...
+
+        actualResults = computeActual("SELECT * FROM test_shard_uuid where \"$shard_uuid\" = '" + arbitraryUuid + "'");
```
Comment (electrum) [inline presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java]: Use format()

File: presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java [hunk 3]
```diff
@@ -74,12 +76,22 @@ public void testShardUuidHiddenColumn()
...
+        actualRows = actualResults.getMaterializedRows();
```
Comment (electrum) [inline presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java]: Inline this into the assert

File: presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java [hunk 4]
```diff
@@ -74,12 +76,22 @@ public void testShardUuidHiddenColumn()
...
+        assertNotEquals(actualRows.size(), 0);
+        actualResults = computeActual("SELECT * FROM test_shard_uuid where \"$shard_uuid\" = 'foo'");
+        actualRows = actualResults.getMaterializedRows();
```
Comment (electrum) [inline presto-raptor/src/test/java/com/facebook/presto/raptor/TestRaptorDistributedQueries.java]: Inline

**Comment by electrum** [comment]
Looks good
