### PR TITLE
Fix unary operator PLUS

### LINKED ISSUE #2594: Unsupported unary operator: PLUS
```
presto:di> select +3;
Query 20150325_185715_19163_dmkgn failed: Unsupported unary operator: PLUS
java.lang.UnsupportedOperationException: Unsupported unary operator: PLUS
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticUnary(ExpressionAnalyzer.java:496)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticUnary(ExpressionAnalyzer.java:208)
	at com.facebook.presto.sql.tree.ArithmeticUnaryExpression.accept(ArithmeticUnaryExpression.java:61)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:181)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1019)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeExpression(TupleAnalyzer.java:1064)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:867)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:347)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:132)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:502)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:198)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:184)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:145)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$33(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$133/567685087.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by dain**
Fixes #2594

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 1]
```diff
@@ -487,7 +487,7 @@ protected Type visitArithmeticUnary(ArithmeticUnaryExpression node, AnalysisCont
                         throw new SemanticException(TYPE_MISMATCH, node, "Unary '+' operator cannot by applied to %s type", type);
                     }
                     expressionTypes.put(node, type);
-                    break;
+                    return type;
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: Hah, nice. How did we miss that?
