### PR TITLE
Detect quick worker reboots and fail queries

### LINKED ISSUE #2330: Detect quick worker restarts and fail queries immediately
When a worker restart, the engine may not notice the change and wait for work that will never complete.  An easy fix for this is to add the node instance id to task info and then the `HttpRemoteTask` would see the change and fail the task.

This issue is identified by having a task stuck in the RUNNING state with 0 splits assigned.  If there are multiple queries, they will all be stuck on the same node or nodes that rebooted.

### PR DESCRIPTION
**Pull request by dain**
If a worker reboots quickly, the engine may think it is the same process and
will wait for results forever.  This change adds the process unique worker
instance id to the task info and if that changes, the query is failed
immediately.

Fixes #2330

### CODE REVIEW

**Comment by electrum** [comment]
This phrase is weird "This change adds the process unique worker instance id"

File: presto-main/src/main/java/com/facebook/presto/server/ExecuteResource.java [hunk 1]
```diff
@@ -140,19 +140,24 @@ private ResultsPageIterator(StatementClient client)
...
+                    if (data != null) {
+                        return data;
+                    }
                 }
-            }
 
-            if (client.isFailed()) {
-                throw internalServerError(failureMessage(client.finalResults()));
-            }
+                if (client.isFailed()) {
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/server/ExecuteResource.java]: This formatting change looks weird

File: presto-main/src/main/java/com/facebook/presto/util/Failures.java [hunk 2]
```diff
@@ -39,6 +39,11 @@
             "The node may have crashed or be under too much load. " +
             "This is probably a transient issue, so please retry your query in a few minutes.";
 
+    public static final String WORKER_RESTARTED_ERROR = "" +
+            "A worker node running your query has restarted. " +
+            "The node may have crashed or be under too much load. " +
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/util/Failures.java]: Factor out the last two sentences?

File: presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java [hunk 3]
```diff
@@ -334,6 +344,15 @@ private synchronized void updateTaskInfo(TaskInfo newValue, List<TaskSource> sou
             return true;
         });
 
+        if (workerRestarted.get()) {
+            PrestoException exception = new PrestoException(TOO_MANY_REQUESTS_FAILED,
+                    format("%s (%s)",
+                            WORKER_RESTARTED_ERROR,
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java]: Put the args on the same line as the format call

File: presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java [hunk 4]
```diff
@@ -334,6 +344,15 @@ private synchronized void updateTaskInfo(TaskInfo newValue, List<TaskSource> sou
             return true;
         });
 
+        if (workerRestarted.get()) {
+            PrestoException exception = new PrestoException(TOO_MANY_REQUESTS_FAILED,
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java]: This should be `WORKER_RESTARTED`

File: presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java [hunk 5]
```diff
@@ -322,7 +325,14 @@ private synchronized void updateTaskInfo(TaskInfo newValue, List<TaskSource> sou
         }
 
         // change to new value if old value is not changed and new value has a newer version
+        AtomicBoolean workerRestarted = new AtomicBoolean();
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/server/HttpRemoteTask.java]: The good old atomic-variable-in-a-closure trick

**Comment by electrum** [comment]
Looks good
