### PR TITLE
Fix ArrayType.equalTo to work with comparable non-orderable types

### LINKED ISSUE #3542: Fix ArrayType.equalTo to work with comparable, non-orderable types
This query should work
```
select count(*), x
from (
  select
    array[map(array[y], array[y])],
    y
  from
    (values 1, 1) t(y)
) u(x, v)
group by x;
```

but it fails with 
```
java.lang.UnsupportedOperationException: map<bigint,bigint> type is not ordered
	at com.facebook.presto.spi.type.AbstractType.compareTo(AbstractType.java:87)
	at com.facebook.presto.type.ArrayType.compareTo(ArrayType.java:107)
	at com.facebook.presto.type.ArrayType.equalTo(ArrayType.java:81)
	at com_facebook_presto_$gen_PagesHashStrategy_29762.positionEqualsRow(Unknown Source)
	at com.facebook.presto.operator.MultiChannelGroupByHash.positionEqualsCurrentRow(MultiChannelGroupByHash.java:371)
	at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:242)
	at com.facebook.presto.operator.MultiChannelGroupByHash.getGroupIds(MultiChannelGroupByHash.java:199)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.processPage(HashAggregationOperator.java:294)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.access$200(HashAggregationOperator.java:256)
	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:210)
```

### PR DESCRIPTION
**Pull request by raghavsethi**
Attempt to fix #3542. Still having some trouble passing the new test, because it's not clear how comparable non-orderable types should be handled at lower layers.

### CODE REVIEW

File: presto-spi/src/main/java/com/facebook/presto/spi/type/AbstractType.java [hunk 1]
```diff
@@ -84,6 +84,9 @@ public boolean equalTo(Block leftBlock, int leftPosition, Block rightBlock, int
     @Override
     public int compareTo(Block leftBlock, int leftPosition, Block rightBlock, int rightPosition)
     {
+        if (!isOrderable()) {
+            throw new UnsupportedOperationException(getTypeSignature() + " type is not ordered");
+        }
```
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/AbstractType.java]: Remove these 3 lines, and add

    if (!elementType.isOrderable()) {
        throw new UnsupportedOperationException(getTypeSignature() + " type is not ordered");
    }

to the beginning of `ArrayType.compareTo`.

File: presto-main/src/test/java/com/facebook/presto/type/TestArrayEqualOperator.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import com.facebook.presto.spi.block.BlockBuilderStatus;
+import com.facebook.presto.spi.type.Type;
+
+import java.util.List;
+
+import static com.facebook.presto.type.ColorType.COLOR;
+import static com.facebook.presto.spi.type.TypeSignature.parseTypeSignature;
+import static com.facebook.presto.util.StructuralTestUtil.arrayBlockOf;
+
+public class TestArrayEqualOperator
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/type/TestArrayEqualOperator.java]: Call this `TestColorArrayType`.

File: presto-main/src/test/java/com/facebook/presto/type/TestArrayEqualOperator.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        arrayType.writeObject(blockBuilder, arrayBlockOf(COLOR, 1, 2, 3));
+        arrayType.writeObject(blockBuilder, arrayBlockOf(COLOR, 1, 2, 3));
+        arrayType.writeObject(blockBuilder, arrayBlockOf(COLOR, 100, 200, 300));
+        return blockBuilder.build();
+    }
+
+    @Override
+    protected Object getGreaterValue(Object value)
+    {
+        Block block = (Block) value;
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/type/TestArrayEqualOperator.java]: `throw new UnsupportedOperationException()`

**Comment by haozhun** [comment]
Let me know when you address the comments.

**Comment by haozhun** [comment]
@cberner This pull request seems good to me. Please take a look and then assign back to me.
@raghavsethi squash your commits.

**Comment by cberner** [comment]
looks good
